#!/bin/bash

export FOREGROUND="#d9d9d9"
export BACKGROUND="#4a4a4a"
export BOLD="#e9e9e9"
export SELECTION="#007172"
export DARKER_SELECTION="#"

export NORMAL_BLACK="#606060"
export BRIGHT_BLACK="#757575"
export NORMAL_RED="#df9a98"
export BRIGHT_RED="#e07798"
export NORMAL_GREEN="#719672"
export BRIGHT_GREEN="#97bb98"
export NORMAL_YELLOW="#e0bb71"
export BRIGHT_YELLOW="#ffdd98"
export NORMAL_BLUE="#96bbdc"
export BRIGHT_BLUE="#badcfb"
export NORMAL_MAGENTA="#dfbdbc"
export BRIGHT_MAGENTA="#ffbebc"
export NORMAL_CYAN="#97bcbc"
export BRIGHT_CYAN="#96ddde"
export NORMAL_WHITE="#d8d8d8"
export BIRGHT_WHITE="#e9e9e9"

