#!/bin/bash
export TMUX_LIGHT_SEGMENT_FG="#d9d9d9"
export TMUX_LIGHT_SEGMENT_BG="#4a4a4a"

# Windows
export TMUX_CURRENT_WINDOW_FG="#606060"
export TMUX_CURRENT_WINDOW_BG="#97bcbc"
export TMUX_CURRENT_WINDOW_FG_ZOOMED="$TMUX_LIGHT_SEGMENT_FG"
export TMUX_CURRENT_WINDOW_BG_ZOOMED="$TMUX_LIGHT_SEGMENT_BG"

export TMUX_WINDOW_FG="#d9d9d9"
export TMUX_WINDOW_BG="#4a4a4a"

# Panes
export TMUX_PANE_ACTIVE_BORDER_FG="#e0bb71"
export TMUX_PANE_BORDER_FG="#e0bb71"
export TMUX_PANE_BG="#4a4a4a"

# Messages
export TMUX_MESSAGE_FG="#d9d9d9"
export TMUX_MESSAGE_BG="#4a4a4a"
export TMUX_MESSAGE_COMMAND_FG="#d9d9d9"
export TMUX_MESSAGE_COMMAND_BG="#4a4a4a"

# Dynamic segments
export TMUX_DARK_SEGMENT_FG="#9a1200"
export TMUX_DARK_SEGMENT_BG="#006f00"
