#!/bin/bash

# Vim

VIM_THEME="gruvbox-dark"
VIM_ALE_ERROR_FG="#fb4934"
VIM_ALE_ERROR_BG="#3c3836"
VIM_ALE_WARNING_FG="#fe8019"
VIM_ALE_WARNING_BG="#3c3836"

# Status bar background
TMUX_STATUS_BG="#cdcdcd"

# Borders
TMUX_PANE_ACTIVE_BORDER_FG="#2c2c2c"
TMUX_PANE_BORDER_FG="#cdcdcd"

# Messages
TMUX_MESSAGE_COMMAND_FG="#2c2c2c"
TMUX_MESSAGE_COMMAND_BG="#cdcdcd"
TMUX_MESSAGE_FG="#2c2c2c"
TMUX_MESSAGE_BG="#cdcdcd"

# Status bar segments (session and hostname)
TMUX_LIGHT_SEGMENT_FG="#f9a825"
TMUX_LIGHT_SEGMENT_BG="#2c2c2c"

# Dynamic segments
TMUX_DARK_SEGMENT_FG="#c62828"
TMUX_DARK_SEGMENT_BG="#616161"

# Windows
TMUX_CURRENT_WINDOW_FG="#2c2c2c"
TMUX_CURRENT_WINDOW_BG="#00838f"
TMUX_WINDOW_FG="#616161"
TMUX_WINDOW_BG="#eeeeee"
